sudo: false
language: python
python:
  - "3.6"

install:
  - pip install -r test-requirements.txt

script:
  - pytest -v --cov --cov-report term-missing
  - mypy --strict --strict-boolean src/typed_graphs
  - flake8 src/typed_graphs

after_success:
  - coveralls
