sudo: false
language: python
python:
  - "3.6"

install:
  - pip install -r test-requirements.txt

script:
  - pytest -v --cov --cov-report term-missing
  - mypy --strict .
  - flake8

after_success:
  - coveralls